### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by fregante**

### CODE REVIEW

**Comment by schuon** [comment]
@bfred-it thanks man!

**Comment by fregante** [comment]
You're welcome. It's still a bit buggy so I'll send another pr later

**Comment by schuon** [comment]
Much appreciated. If you spot a way to figure out if the item count % 25 = 0 because it's actually 25 items or if there are more to be loaded that would be awesome. Couldn't spot anything in the code that would tell me.

**Comment by fregante** [comment]
Unfortunately I couldn't either.

**Pull request merged**
